//Converts .png.json files into UV coordinates for top-left (tl), top-right (tr), bottom-left (bl), and bottom-right (br) coordinates
package atlas_parser

import "core:mem"
import "core:encoding/json"
import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:sort"
import "core:strings"

UV :: struct {
	tl: [2]f32,
	tr: [2]f32,
	bl: [2]f32,
	br: [2]f32,
}

SubTexture :: struct {
	x: f64,
	y: f64,
	w: f64,
	h: f64,
}

Texture :: struct {
	tw: f64,
	th: f64,
}

main :: proc() {
	when ODIN_DEBUG {
		track: mem.Tracking_Allocator
		mem.tracking_allocator_init(&track, context.allocator)
		context.allocator = mem.tracking_allocator(&track)
		defer {
			if len(track.allocation_map) > 0 {
				fmt.eprintfln("=== %v allocation(s) not freed ===", len(track.allocation_map))
			}
			for _, entry in track.allocation_map {
				fmt.eprintf("%v bytes @ %v\n", entry.size, entry.location)
			}
			mem.tracking_allocator_destroy(&track)
		}
	}
	to_dir := #directory + ".."
	os.change_directory(to_dir)
	dir, e := os.open(to_dir)
	if e != nil {
		fmt.eprintln("Unable to open directory:", e)
		os.exit(1)
	}
	defer os.close(dir)
	fis: []os.File_Info = ---
	fis, e = os.read_dir(dir, 0, context.allocator)
	if e != nil {
		fmt.eprintln("Unable to open directory:", e)
		os.exit(1)
	}
	defer os.file_info_slice_delete(fis, context.allocator)
	next_file: for fi in fis {
		dot_i := strings.index(fi.name, ".")
		if dot_i == -1 do continue
		stem := fi.name[:dot_i]
		ext := filepath.long_ext(fi.name)
		if fi.type == .Regular && ext == ".png.json" {
			fmt.printfln("Creating texture coordinates with '{}'", fi.name)
			file_str: []u8 = ---
			file_str, e = os.read_entire_file(fi.name, context.allocator)
			if e != nil {
				fmt.eprintfln("Unable to open '{}': {}", fi.name, e)
				continue
			}
			defer delete(file_str)
			json_map, json_e := json.parse(file_str)
			if json_e != .None {
				fmt.eprintfln("Unable to open '{}': {}", fi.name, json_e)
				continue
			}
			defer json.destroy_value(json_map)
			json_v := json_map.(json.Object)
			texture: Maybe(Texture)
			subtexture_array := make([dynamic]string)
			defer delete(subtexture_array)
			subtexture_atlas := make(map[string]SubTexture)
			defer {
				for k, _ in subtexture_atlas {
					delete(k)
				}
				delete(subtexture_atlas)
			}
			for k, vmap in json_v {
				if k != "!FILE" {
					k_clone := strings.clone(k)
					if k_clone in subtexture_atlas {
						fmt.eprintfln("Error Cloned key: {}. Skipping file '{}'", k_clone, fi.name)
						delete(k_clone)
						continue next_file
					}
					subtexture_atlas[k_clone] = {
						h = vmap.(json.Object)["h"].(json.Float),
						w = vmap.(json.Object)["w"].(json.Float),
						x = vmap.(json.Object)["x"].(json.Float),
						y = vmap.(json.Object)["y"].(json.Float),
					}
					append(&subtexture_array, k_clone)
				} else {
					texture = Texture {
						th = vmap.(json.Object)["th"].(json.Float),
						tw = vmap.(json.Object)["tw"].(json.Float),
					}
				}
			}
			if texture == nil {
				fmt.eprintfln("Key '!FILE' is required. Skipping file '{}'", fi.name)
				continue next_file
			}
			sb := strings.builder_make()
			defer strings.builder_destroy(&sb)
			sort.quick_sort(subtexture_array[:])
			fmt.sbprintf(
				&sb,
				"package assets\n\n" +
				"//Generated by ./assets/atlas_parser/main.odin\n\n" +
				"import \"./atlas_parser\"\n\n",
			)
			fmt.sbprintf(&sb, "{}_bytes :: #load(\"./{}.png\", string)\n\n", stem, stem)
			fmt.sbprintf(&sb, "{} :: enum {{\n", stem)
			for k, _ in subtexture_array {
				fmt.sbprintfln(&sb, "\t{},", k)
			}
			fmt.sbprintf(&sb, "}}\n\n{}_uv := [{}]atlas_parser.UV {{\n", stem, stem)
			for k, _ in subtexture_array {
				sub_b := subtexture_atlas[k]
				fmt.sbprintfln(
					&sb,
					"\t .%v = {{\n\t\ttl = {{%.10f, %.10f}}, \n\t\ttr = {{%.10f, %.10f}}, \n\t\tbl = {{%.10f, %.10f}}, \n\t\tbr = {{%.10f, %.10f}},\n\t}},",
					k,
					sub_b.x / (texture.(Texture)).tw,
					sub_b.y / (texture.(Texture)).th,
					(sub_b.x + sub_b.w) / (texture.(Texture)).tw,
					sub_b.y / (texture.(Texture)).th,
					sub_b.x / (texture.(Texture)).tw,
					(sub_b.y + sub_b.h) / (texture.(Texture)).th,
					(sub_b.x + sub_b.w) / (texture.(Texture)).tw,
					(sub_b.y + sub_b.h) / (texture.(Texture)).th,
				)
			}
			strings.write_string(&sb, "}\n")
			img_odin_file := fmt.aprintf("{}.odin", stem)
			defer delete(img_odin_file)
			write_e := os.write_entire_file_from_string(img_odin_file, strings.to_string(sb))
			if write_e != nil {
				fmt.eprintfln("Unable to write to file '{}': {}", img_odin_file, write_e)
			}
			fmt.printfln("Written texture coordinates to '{}'", img_odin_file)
		}
	}
	fmt.println("Success")
}
